# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Changelog/Version Management
on:
  pull_request:
    branches: [ main ]
jobs:
  run-standard-version:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Config git
      run: |
        git config --global user.name $GITHUB_ACTOR
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
    - name: Run Standard Version
      run: |
        npx standard-version
        git fetch origin $GITHUB_HEAD_REF
        git push -f --follow-tags origin HEAD:$GITHUB_HEAD_REF
    # - name: output env
    #   run: env
    # - name: Push changes
    #   run: |
    #     git fetch origin $GITHUB_HEAD_REF
    #     git push origin HEAD:$GITHUB_HEAD_REF